/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_edd.pkg1;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new java.awt.Label();
        CargarArchivo = new java.awt.Button();
        Integrantes = new java.awt.Label();
        SofiaRomero = new java.awt.Label();
        AntonyCen1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Sopa de letras");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 30));
        Titulo.getAccessibleContext().setAccessibleName("titulo");
        Titulo.getAccessibleContext().setAccessibleDescription("");

        CargarArchivo.setLabel("Cargar Archivo");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(CargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        Integrantes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Integrantes.setForeground(new java.awt.Color(255, 255, 255));
        Integrantes.setText("Integrantes:");
        jPanel1.add(Integrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 90, 30));

        SofiaRomero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SofiaRomero.setForeground(new java.awt.Color(255, 255, 255));
        SofiaRomero.setText("Sofia Romero");
        jPanel1.add(SofiaRomero, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 90, 30));

        AntonyCen1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AntonyCen1.setForeground(new java.awt.Color(255, 255, 255));
        AntonyCen1.setText("Antony Cen");
        jPanel1.add(AntonyCen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int resultado = fileChooser.showOpenDialog(this);
        
        if(resultado == JFileChooser.APPROVE_OPTION){
            java.io.File archivoSeleccionado = fileChooser.getSelectedFile();
            
            if (archivoSeleccionado.getName().toLowerCase().endsWith(".txt")) {
               JOptionPane.showMessageDialog(this, "Archivo TXT seleccionado: " + archivoSeleccionado.getAbsolutePath(), "Archivo Seleccionado", JOptionPane.INFORMATION_MESSAGE);
                
            
                
                try (BufferedReader reader = new BufferedReader(
                    new InputStreamReader(new FileInputStream(archivoSeleccionado), StandardCharsets.UTF_8))
                ) {
                    StringBuilder content = new StringBuilder();
                    String line;
                    if ((line = reader.readLine()) != null) {
                        content.append(line);
                        while ((line = reader.readLine()) != null) {
                            content.append("\n").append(line);
                        }
                    }
                    System.out.println(content);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this,
                        "Error al leer archivo: " + ex.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                }


                
            
            } else {
                JOptionPane.showMessageDialog(this, "El archivo seleccionado no es un archivo .txt válido.", "Error de Selección", JOptionPane.WARNING_MESSAGE);
            }
        } else if (resultado == JFileChooser.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(this, "Selección de archivo cancelada.", "Cancelado", JOptionPane.INFORMATION_MESSAGE);
        } else if (resultado == JFileChooser.ERROR_OPTION) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al abrir el diálogo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CargarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label AntonyCen1;
    private java.awt.Button CargarArchivo;
    private java.awt.Label Integrantes;
    private java.awt.Label SofiaRomero;
    private java.awt.Label Titulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
