package proyecto_edd.pkg1;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sofia Romero
 */
public class SegundaInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form SegundaInterfaz
     */
    public static String[] listaLetras ;
    public static String[] listaPalabras ;
    public static Grafo jj;
    
    
    public SegundaInterfaz(String[] listaLetras, String[] listaPalabras, Grafo jj) {
        initComponents();
        this.listaLetras= listaLetras;
        this.listaPalabras = listaPalabras;
        this.jj = jj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        DFS = new java.awt.Button();
        BFS = new java.awt.Button();
        label1 = new java.awt.Label();
        palabraEspecifica = new java.awt.Button();
        buscaPalabraEspecifico = new javax.swing.JTextField();
        DFSbusqueda = new java.awt.TextArea();
        BFSbusqueda = new java.awt.TextArea();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DFS.setLabel("Buscar por DFS");
        DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFSActionPerformed(evt);
            }
        });
        jPanel1.add(DFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        BFS.setLabel("Buscar por BFS");
        BFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFSActionPerformed(evt);
            }
        });
        jPanel1.add(BFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(102, 102, 102));
        label1.setText("Buscar Palabras");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 40));

        palabraEspecifica.setLabel("Buscar palabra");
        palabraEspecifica.setName(""); // NOI18N
        palabraEspecifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraEspecificaActionPerformed(evt);
            }
        });
        jPanel1.add(palabraEspecifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        buscaPalabraEspecifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaPalabraEspecificoActionPerformed(evt);
            }
        });
        jPanel1.add(buscaPalabraEspecifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 180, -1));
        jPanel1.add(DFSbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 200, 140));
        jPanel1.add(BFSbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFSActionPerformed
        
        StringBuilder encuentro = new StringBuilder();
        for(int i = 0; i< listaPalabras.length; i++){
            //System.out.println(listaPalabras[i]);
            boolean pp = jj.buscarPalabraDFS(listaPalabras[i], listaLetras);
//            if(pp == true){
//                DFSbusqueda.setText(listaPalabras[i]);
//            }else{
//                DFSbusqueda.setText("Diccionario vacio");
//            }
            if(pp){
                encuentro.append(listaPalabras[i]).append("\n");
            }
        }
        
        if(encuentro.length()> 0){
            DFSbusqueda.setText(encuentro.toString());
        }else{
            DFSbusqueda.setText("Diccionario vacio");
        }
        
        
        
    }//GEN-LAST:event_DFSActionPerformed

    private void palabraEspecificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraEspecificaActionPerformed
        // TODO add your handling code here:
        
        String palabra = (buscaPalabraEspecifico.getText()).toUpperCase();
        boolean si = jj.buscarPalabraDFS(palabra, listaLetras);
        if(si == true){
         JOptionPane.showMessageDialog(this, "Palabra encontrada");
        }else {
         JOptionPane.showMessageDialog(this, "La palabra no se encuentra");
        }
        
        
    }//GEN-LAST:event_palabraEspecificaActionPerformed

    private void BFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFSActionPerformed
        // TODO add your handling code here:
        StringBuilder encuentro = new StringBuilder();
        
        for(int i = 0; i< listaPalabras.length; i++){
            //System.out.println(listaPalabras[i]);
            boolean kk = jj.buscarPalabraBFS(listaPalabras[i], listaLetras);  
        
            if(kk){
                encuentro.append(listaPalabras[i]).append("\n");
            }
        }
        
        if(encuentro.length()> 0){
            BFSbusqueda.setText(encuentro.toString());
        }else{
            BFSbusqueda.setText("Diccionario vacio");
        }
    }//GEN-LAST:event_BFSActionPerformed

    private void buscaPalabraEspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaPalabraEspecificoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaPalabraEspecificoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundaInterfaz(listaLetras, listaPalabras, jj).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BFS;
    private java.awt.TextArea BFSbusqueda;
    private java.awt.Button DFS;
    private java.awt.TextArea DFSbusqueda;
    private javax.swing.JTextField buscaPalabraEspecifico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private java.awt.Label label1;
    private java.awt.Button palabraEspecifica;
    // End of variables declaration//GEN-END:variables
}
